development:
  adapter: mysql2
  database: university_career_tracker_dev
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  database: university_career_tracker_test
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
